sudo: required
services:
  - docker

script:
  - curl -L https://raw.githubusercontent.com/experimental-platform/build-scripts/master/buildimg.sh | bash

# language: ruby
# rvm:
#   - 2.3.0
# before_install: gem install bundler -v 1.11.2
